// crm-automations
//
// Runs the CRM-side automations (idempotent, safe to call every few minutes
// via cron and directly from the app after a reservation is saved):
//
//   task_templates    – tasks generated by the CRM itself, relative to the
//                       reservation date or the trigger moment, pushed to GHL
//   quote_documents   – GHL offerte/contract sent → inquiry to "Offerte
//                       verzonden" (+ tasks); signed → "Definitieve
//                       reservering" (+ option → confirmed)
//   option_expiry     – warn before an option expires, expire it afterwards
//   post_event        – event took place → contact = klant, inquiry to
//                       facturatie, GHL tags (review request etc.)
//   inbound_reply_sla – unanswered inbound message → task
//   contact_tags      – CRM contact status mirrored as GHL tag
//
// Every automation writes an automation_runs row keyed on a dedupe_key and
// every generated task carries a unique automation_key, so a rerun never
// creates a second task or moves a status twice.

import { createClient } from "npm:@supabase/supabase-js@2";
import {
  GHL_API_BASE,
  buildAppointmentPayload,
  buildTaskPayload,
  jsonResponse,
  readError,
} from "../_shared/ghlCommon.ts";
import {
  addDays,
  amsterdamDate,
  inboundOverdue,
  isForwardStatusChange,
  isQuoteDocument,
  optionExpiryDate,
  optionState,
  planTasks,
  tagsForContactStatus,
  withNameSuffix,
  type OptionExpiryConfig,
  type PlannedTask,
  type QuoteDocumentsConfig,
  type TaskTemplate,
} from "../_shared/automations.ts";

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

interface Settings {
  enabled: boolean;
  config: Record<string, any>;
}

interface Results {
  today: string;
  scope: string;
  tasks_created: number;
  tasks_pushed: number;
  inquiries_updated: number;
  bookings_updated: number;
  contacts_updated: number;
  ghl_tags_pushed: number;
  options_warned: number;
  options_expired: number;
  errors: string[];
  details: string[];
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' } });

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
  const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const GHL_API_KEY = Deno.env.get('GHL_API_KEY') || '';
  const GHL_LOCATION_ID = Deno.env.get('GHL_LOCATION_ID') || '';
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY);
  const ghlHeaders = {
    'Authorization': `Bearer ${GHL_API_KEY}`,
    'Content-Type': 'application/json',
    'Version': '2021-07-28',
  };
  const ghlEnabled = Boolean(GHL_API_KEY && GHL_LOCATION_ID);

  // Auth: the cron job calls with the project's anon key; the app calls with the
  // signed-in user's JWT. Anything else is rejected. Only signed-in users get
  // the detailed log (it contains contact names).
  const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY') || '';
  const authHeader = req.headers.get('Authorization') || '';
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : '';
  let caller: 'cron' | 'user' | null = null;
  if (token && ANON_KEY && token === ANON_KEY) {
    caller = 'cron';
  } else if (token) {
    const anonClient = createClient(SUPABASE_URL, ANON_KEY || token, { global: { headers: { Authorization: authHeader } } });
    const { data: { user } } = await anonClient.auth.getUser();
    if (user) caller = 'user';
  }
  if (!caller) return jsonResponse({ error: 'Unauthorized' }, 401);

  let body: Record<string, any> = {};
  try { body = await req.json(); } catch { body = {}; }
  const bookingScope: string | null = body.booking_id || null;
  const dryRun = body.dry_run === true;

  const today = amsterdamDate();
  const results: Results = {
    today, scope: bookingScope ? `booking:${bookingScope}` : 'all',
    tasks_created: 0, tasks_pushed: 0, inquiries_updated: 0, bookings_updated: 0,
    contacts_updated: 0, ghl_tags_pushed: 0, options_warned: 0, options_expired: 0,
    errors: [], details: [],
  };

  try {
    // ---------------------------------------------------------------- setup
    const { data: settingRows } = await supabase.from('automation_settings').select('key, enabled, config, user_id');
    const settings = new Map<string, Settings>();
    for (const row of settingRows || []) settings.set(row.key, { enabled: row.enabled === true, config: row.config || {} });
    const isOn = (key: string) => settings.get(key)?.enabled === true;
    const cfg = <T,>(key: string, defaults: T): T => ({ ...defaults, ...(settings.get(key)?.config || {}) });

    const { data: templateRows } = await supabase.from('task_templates').select('*').eq('enabled', true).order('sort_order');
    const templates: (TaskTemplate & { user_id: string })[] = (templateRows || []).map((t: any) => ({
      id: t.id, trigger: t.trigger, title: t.title, description: t.description, anchor: t.anchor,
      offset_days: Number(t.offset_days) || 0, assignees: Array.isArray(t.assignees) ? t.assignees : [],
      priority: t.priority || 'normal', enabled: t.enabled === true, user_id: t.user_id,
    }));
    const templatesFor = (trigger: TaskTemplate['trigger']) => templates.filter((t) => t.trigger === trigger);

    const { data: anyProfile } = await supabase.from('profiles').select('id').order('created_at').limit(1).maybeSingle();
    const ownerId: string | null = (settingRows?.[0]?.user_id) || templates[0]?.user_id || anyProfile?.id || null;
    if (!ownerId) return jsonResponse({ success: false, error: 'No user found' });

    // Contacts (for names, GHL ids and tags) — loaded once
    const contacts = await fetchAll(supabase, 'contacts', 'id, first_name, last_name, company, company_id, ghl_contact_id, status, tags, updated_at');
    const contactById = new Map<string, any>(contacts.map((c: any) => [c.id, c]));
    const contactName = (c: any | null | undefined) => c ? `${c.first_name || ''} ${c.last_name || ''}`.trim() : '';

    // Room → GHL calendar mapping (for pushing booking changes)
    const { data: roomRows } = await supabase.from('room_settings').select('room_name, ghl_calendar_id').not('ghl_calendar_id', 'is', null);
    const calendarForRoom = new Map<string, string>((roomRows || []).map((r: any) => [r.room_name, r.ghl_calendar_id]));

    // -------------------------------------------------------------- helpers
    const recordRun = async (automation: string, dedupeKey: string, entityType: string, entityId: string | null, result: Record<string, unknown>, templateId: string | null = null): Promise<boolean> => {
      if (dryRun) return true;
      const { data, error } = await supabase
        .from('automation_runs')
        .upsert({ user_id: ownerId, automation, template_id: templateId, entity_type: entityType, entity_id: entityId, dedupe_key: dedupeKey, result }, { onConflict: 'dedupe_key', ignoreDuplicates: true })
        .select('id');
      if (error) { results.errors.push(`run:${dedupeKey}:${error.message}`); return false; }
      return Boolean(data && data.length > 0); // false = already ran before
    };

    const hasRun = async (dedupeKey: string): Promise<boolean> => {
      const { data } = await supabase.from('automation_runs').select('id').eq('dedupe_key', dedupeKey).maybeSingle();
      return Boolean(data);
    };

    /** Insert planned tasks (idempotent on automation_key) and push them to GHL. */
    const createTasks = async (
      planned: PlannedTask[],
      link: { contact_id?: string | null; company_id?: string | null; inquiry_id?: string | null; booking_id?: string | null },
      userId: string,
    ) => {
      if (!planned.length) return;
      if (dryRun) { results.tasks_created += planned.length; return; }
      const rows = planned.map((t) => ({
        user_id: userId,
        title: t.title,
        description: t.description,
        status: 'open',
        priority: t.priority,
        due_date: t.due_date,
        assigned_to: t.assigned_to,
        contact_id: link.contact_id || null,
        company_id: link.company_id || null,
        inquiry_id: link.inquiry_id || null,
        booking_id: link.booking_id || null,
        automation_key: t.automation_key,
      }));
      const { data: inserted, error } = await supabase
        .from('tasks')
        .upsert(rows, { onConflict: 'automation_key', ignoreDuplicates: true })
        .select('id, title, description, status, due_date, due_time, contact_id');
      if (error) { results.errors.push(`tasks:${error.message}`); return; }
      const created = inserted || [];
      results.tasks_created += created.length;
      for (const t of created) results.details.push(`taak "${t.title}" (${t.due_date})`);

      // Push to GHL right away so both systems show the task within a minute
      if (!ghlEnabled) return;
      const contact = link.contact_id ? contactById.get(link.contact_id) : null;
      if (!contact?.ghl_contact_id) return;
      for (const t of created) {
        try {
          await delay(150);
          const res = await fetch(`${GHL_API_BASE}/contacts/${contact.ghl_contact_id}/tasks`, {
            method: 'POST', headers: ghlHeaders, body: JSON.stringify(buildTaskPayload(t)),
          });
          if (res.ok) {
            const created = await res.json();
            if (created.task?.id) await supabase.from('tasks').update({ ghl_task_id: created.task.id }).eq('id', t.id);
            results.tasks_pushed++;
          } else {
            results.errors.push(`ghl-task:${t.id}:${await readError(res)}`);
          }
        } catch (e) { results.errors.push(`ghl-task:${t.id}:${String(e)}`); }
      }
    };

    /** Push a booking's current state to its GHL appointment (status/title change). */
    const pushBooking = async (booking: any) => {
      if (!ghlEnabled || !booking.ghl_event_id) return;
      const calendarId = calendarForRoom.get(booking.room_name);
      const contact = booking.contact_id ? contactById.get(booking.contact_id) : null;
      if (!calendarId || !contact?.ghl_contact_id) return;
      try {
        const payload = buildAppointmentPayload(booking, calendarId, GHL_LOCATION_ID, contact.ghl_contact_id);
        const res = await fetch(`${GHL_API_BASE}/calendars/events/appointments/${booking.ghl_event_id}`, {
          method: 'PUT', headers: { ...ghlHeaders, 'Version': '2021-04-15' }, body: JSON.stringify(payload),
        });
        if (!res.ok) results.errors.push(`ghl-booking:${booking.id}:${await readError(res)}`);
        else await res.text();
      } catch (e) { results.errors.push(`ghl-booking:${booking.id}:${String(e)}`); }
    };

    /** Move an inquiry forward in the pipeline (CRM-origin change → GHL follows via the normal sync). */
    const advanceInquiry = async (inquiry: any, nextStatus: string, reason: string) => {
      if (!inquiry || !nextStatus || !isForwardStatusChange(inquiry.status, nextStatus)) return false;
      if (dryRun) { results.inquiries_updated++; return true; }
      const { error } = await supabase.from('inquiries').update({ status: nextStatus, status_reason: reason }).eq('id', inquiry.id);
      if (error) { results.errors.push(`inquiry:${inquiry.id}:${error.message}`); return false; }
      inquiry.status = nextStatus;
      results.inquiries_updated++;
      results.details.push(`aanvraag ${inquiry.display_number || inquiry.id} → ${nextStatus}`);
      return true;
    };

    /** Add GHL tags to a contact (CRM tags column + GHL). */
    const addContactTags = async (contact: any, tags: string[]) => {
      const current: string[] = Array.isArray(contact.tags) ? contact.tags : [];
      const missing = tags.filter((t) => t && !current.some((c) => c.toLowerCase() === t.toLowerCase()));
      if (!missing.length) return;
      const next = [...current, ...missing];
      if (dryRun) { results.ghl_tags_pushed++; return; }
      const { error } = await supabase.from('contacts').update({ tags: next }).eq('id', contact.id);
      if (error) { results.errors.push(`tags:${contact.id}:${error.message}`); return; }
      contact.tags = next;
      if (ghlEnabled && contact.ghl_contact_id) {
        try {
          await delay(150);
          const res = await fetch(`${GHL_API_BASE}/contacts/${contact.ghl_contact_id}/tags`, {
            method: 'POST', headers: ghlHeaders, body: JSON.stringify({ tags: missing }),
          });
          if (res.ok) { results.ghl_tags_pushed++; await res.text(); }
          else results.errors.push(`ghl-tags:${contact.id}:${await readError(res)}`);
        } catch (e) { results.errors.push(`ghl-tags:${contact.id}:${String(e)}`); }
      }
    };

    const bookingPlaceholders = (b: any) => {
      const c = b.contact_id ? contactById.get(b.contact_id) : null;
      return {
        naam: contactName(c) || b.contact_name || '',
        bedrijf: c?.company || '',
        titel: b.title || '',
        datum: b.date ? `${b.date.slice(8, 10)}-${b.date.slice(5, 7)}-${b.date.slice(0, 4)}` : '',
        zaal: b.room_name || '',
      };
    };

    // ------------------------------------------------------- 1. task templates
    if (isOn('task_templates') && templates.length > 0) {
      const lookbackDays = 14;
      let q = supabase
        .from('bookings')
        .select('id, user_id, date, status, title, contact_name, contact_id, company_id, inquiry_id, room_name, notes, created_at, updated_at, option_expires_at, ghl_event_id, start_hour, start_minute, end_hour, end_minute')
        .gte('date', addDays(today, -lookbackDays));
      if (bookingScope) q = q.eq('id', bookingScope);
      const { data: bookings, error: bErr } = await q;
      if (bErr) results.errors.push(`bookings:${bErr.message}`);

      for (const b of bookings || []) {
        const ph = bookingPlaceholders(b);
        const link = { contact_id: b.contact_id, company_id: b.company_id, inquiry_id: b.inquiry_id, booking_id: b.id };
        const userId = b.user_id || ownerId;
        const recentlyChanged = b.updated_at && Date.now() - Date.parse(b.updated_at) < lookbackDays * 86400000;

        if (b.status === 'confirmed' && b.date >= today) {
          for (const t of templatesFor('booking_confirmed')) {
            await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `booking:${b.id}`, { today, eventDate: b.date, placeholders: ph }), link, userId);
          }
        }
        if (b.status === 'option' && b.date >= today) {
          const placed = b.created_at ? String(b.created_at).slice(0, 10) : today;
          for (const t of templatesFor('booking_option')) {
            await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `booking:${b.id}`, { today, eventDate: b.date, triggerDate: placed, placeholders: ph }), link, userId);
          }
        }
        if (b.status === 'cancelled' && recentlyChanged) {
          for (const t of templatesFor('booking_cancelled')) {
            await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `booking:${b.id}`, { today, eventDate: b.date, triggerDate: today, placeholders: ph }), link, userId);
          }
        }
        // "Evenement heeft plaatsgevonden": only the last two days, so switching
        // a template on does not backfill weeks of old events with tasks due today.
        if (b.status === 'confirmed' && b.date < today && b.date >= addDays(today, -2)) {
          for (const t of templatesFor('event_passed')) {
            await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `booking:${b.id}`, { today, eventDate: b.date, placeholders: ph }), link, userId);
          }
        }
      }
    }

    // ------------------------------------------------------ 2. quote documents
    if (isOn('quote_documents') && !bookingScope) {
      const qc = cfg<QuoteDocumentsConfig>('quote_documents', { sent_status: 'quoted', signed_status: 'confirmed', convert_option_to_confirmed: true, title_keywords: ['offerte', 'contract'] });
      const since = new Date(Date.now() - 30 * 86400000).toISOString();
      const { data: docs, error: dErr } = await supabase
        .from('documents')
        .select('id, user_id, title, document_type, status, contact_id, inquiry_id, company_id, sent_at, signed_at, updated_at, contact_name')
        .gte('updated_at', since)
        .in('status', ['sent', 'viewed', 'signed', 'paid']);
      if (dErr) results.errors.push(`documents:${dErr.message}`);

      for (const doc of docs || []) {
        if (!isQuoteDocument(doc, qc)) continue;
        // Resolve the inquiry: linked directly, otherwise the most recent open inquiry of the contact
        let inquiry: any = null;
        if (doc.inquiry_id) {
          const { data } = await supabase.from('inquiries').select('id, status, display_number, contact_id, company_id, user_id').eq('id', doc.inquiry_id).maybeSingle();
          inquiry = data;
        } else if (doc.contact_id) {
          const { data } = await supabase.from('inquiries').select('id, status, display_number, contact_id, company_id, user_id')
            .eq('contact_id', doc.contact_id).neq('status', 'lost').order('created_at', { ascending: false }).limit(1).maybeSingle();
          inquiry = data;
          if (inquiry && !dryRun) await supabase.from('documents').update({ inquiry_id: inquiry.id }).eq('id', doc.id);
        }
        const contact = doc.contact_id ? contactById.get(doc.contact_id) : null;
        const ph = { naam: contactName(contact) || doc.contact_name || '', bedrijf: contact?.company || '', titel: doc.title || '' };
        const link = { contact_id: doc.contact_id, company_id: doc.company_id || contact?.company_id || null, inquiry_id: inquiry?.id || null, booking_id: null };
        const userId = doc.user_id || ownerId;

        // Sent (or viewed): pipeline → "Offerte verzonden" + follow-up tasks.
        // A document that is already signed skips this step (no "nabellen" for a signed offer).
        const sentKey = `quote_sent:${doc.id}`;
        const alreadySigned = doc.status === 'signed' || doc.status === 'paid';
        if (!(await hasRun(sentKey))) {
          let moved = false;
          if (!alreadySigned) {
            moved = await advanceInquiry(inquiry, qc.sent_status, `Offerte "${doc.title}" verzonden`);
            // The sent document carries the current revision; the next offer for this
            // inquiry becomes revision +1 on the GHL contact fields.
            if (inquiry && !dryRun) {
              const { error: revErr } = await supabase.rpc('bump_offerte_revisie', { p_inquiry_id: inquiry.id });
              if (revErr) results.errors.push(`revisie:${inquiry.id}:${revErr.message}`);
              else {
                await supabase.from('inquiries').update({ offerte_gestaged_op: new Date().toISOString() }).eq('id', inquiry.id);
                try {
                  await fetch(`${SUPABASE_URL}/functions/v1/stage-offerte`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${SERVICE_KEY}` },
                    body: JSON.stringify({ inquiry_id: inquiry.id, bump: false }),
                  }).then((r) => r.text());
                } catch (e) { results.errors.push(`stage-offerte:${inquiry.id}:${String(e)}`); }
              }
            }
            const sentDate = doc.sent_at ? String(doc.sent_at).slice(0, 10) : today;
            for (const t of templatesFor('quote_sent')) {
              await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `document:${doc.id}`, { today, triggerDate: sentDate, placeholders: ph }), link, userId);
            }
          }
          await recordRun('quote_documents', sentKey, 'document', doc.id, { moved, status: doc.status, skipped: alreadySigned, inquiry_id: inquiry?.id || null });
        }

        // Signed/paid: definitive reservation, option → confirmed
        if (doc.status === 'signed' || doc.status === 'paid') {
          const signedKey = `quote_signed:${doc.id}`;
          if (!(await hasRun(signedKey))) {
            const moved = await advanceInquiry(inquiry, qc.signed_status, `Offerte "${doc.title}" getekend`);
            let converted = 0;
            if (qc.convert_option_to_confirmed && inquiry) {
              const { data: options } = await supabase.from('bookings').select('*').eq('inquiry_id', inquiry.id).eq('status', 'option');
              for (const opt of options || []) {
                if (dryRun) { converted++; continue; }
                const { error } = await supabase.from('bookings').update({ status: 'confirmed', status_reason: `Offerte "${doc.title}" getekend`, option_expires_at: null }).eq('id', opt.id);
                if (error) { results.errors.push(`booking:${opt.id}:${error.message}`); continue; }
                converted++;
                results.bookings_updated++;
                results.details.push(`optie ${opt.title} → bevestigd`);
                await pushBooking({ ...opt, status: 'confirmed' });
              }
            }
            for (const t of templatesFor('quote_signed')) {
              await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `document:${doc.id}`, { today, triggerDate: today, placeholders: ph }), link, userId);
            }
            await recordRun('quote_documents', signedKey, 'document', doc.id, { moved, converted, inquiry_id: inquiry?.id || null });
          }
        }
      }
    }

    // --------------------------------------------------------- 3. option expiry
    if (isOn('option_expiry')) {
      const oc = cfg<OptionExpiryConfig>('option_expiry', { default_days_before_event: 14, warn_days_before_expiry: 3, auto_expire: true });
      // Also options whose event date has already passed (they must expire too)
      let q = supabase.from('bookings').select('*').eq('status', 'option').gte('date', addDays(today, -60));
      if (bookingScope) q = q.eq('id', bookingScope);
      const { data: options, error: oErr } = await q;
      if (oErr) results.errors.push(`options:${oErr.message}`);

      for (const opt of options || []) {
        const expiresAt = optionExpiryDate(opt, oc);
        if (!opt.option_expires_at && !dryRun) {
          await supabase.from('bookings').update({ option_expires_at: expiresAt }).eq('id', opt.id);
        }
        const state = optionState(expiresAt, today, oc);
        const ph = { ...bookingPlaceholders(opt), vervalt: `${expiresAt.slice(8, 10)}-${expiresAt.slice(5, 7)}-${expiresAt.slice(0, 4)}` };
        const link = { contact_id: opt.contact_id, company_id: opt.company_id, inquiry_id: opt.inquiry_id, booking_id: opt.id };

        if (state === 'warn' && opt.date >= today) {
          const key = `option_warn:${opt.id}:${expiresAt}`;
          if (!(await hasRun(key))) {
            for (const t of templatesFor('option_expiring')) {
              await createTasks(planTasks({ ...t, title: withNameSuffix(t.title, ph.naam) }, `option:${opt.id}:${expiresAt}`, { today, eventDate: opt.date, triggerDate: today, placeholders: ph }), link, opt.user_id || ownerId);
            }
            results.options_warned++;
            await recordRun('option_expiry', key, 'booking', opt.id, { expires_at: expiresAt, state });
          }
        } else if (state === 'expired' && oc.auto_expire) {
          const key = `option_expired:${opt.id}`;
          if (!(await hasRun(key))) {
            if (!dryRun) {
              const { error } = await supabase.from('bookings').update({ status: 'expired', status_reason: `Optie verlopen op ${ph.vervalt}` }).eq('id', opt.id);
              if (error) { results.errors.push(`expire:${opt.id}:${error.message}`); continue; }
              await pushBooking({ ...opt, status: 'expired' });
            }
            results.options_expired++;
            results.bookings_updated++;
            results.details.push(`optie ${opt.title} verlopen (${ph.vervalt})`);
            await recordRun('option_expiry', key, 'booking', opt.id, { expires_at: expiresAt, state });
          }
        }
      }
    }

    // ------------------------------------------------------------ 4. post event
    if (isOn('post_event')) {
      const pc = cfg<{ inquiry_status: string | null; contact_status: string | null; ghl_tags: string[]; lookback_days: number }>('post_event', { inquiry_status: 'invoiced', contact_status: 'client', ghl_tags: ['klant', 'review-aanvraag'], lookback_days: 14 });
      let q = supabase.from('bookings').select('id, date, title, status, contact_id, inquiry_id').eq('status', 'confirmed').lt('date', today).gte('date', addDays(today, -Math.max(1, pc.lookback_days)));
      if (bookingScope) q = q.eq('id', bookingScope);
      const { data: passed, error: pErr } = await q;
      if (pErr) results.errors.push(`passed:${pErr.message}`);

      for (const b of passed || []) {
        const key = `post_event:${b.id}`;
        if (await hasRun(key)) continue;
        const contact = b.contact_id ? contactById.get(b.contact_id) : null;
        const out: Record<string, unknown> = {};
        if (contact && pc.contact_status && contact.status !== pc.contact_status && contact.status !== 'do_not_contact' && contact.status !== 'inactive') {
          if (!dryRun) {
            const { error } = await supabase.from('contacts').update({ status: pc.contact_status }).eq('id', contact.id);
            if (error) results.errors.push(`contact:${contact.id}:${error.message}`); else { contact.status = pc.contact_status; results.contacts_updated++; }
          }
          out.contact_status = pc.contact_status;
        }
        if (contact && Array.isArray(pc.ghl_tags) && pc.ghl_tags.length) {
          await addContactTags(contact, pc.ghl_tags);
          out.tags = pc.ghl_tags;
        }
        if (b.inquiry_id && pc.inquiry_status) {
          const { data: inquiry } = await supabase.from('inquiries').select('id, status, display_number').eq('id', b.inquiry_id).maybeSingle();
          out.inquiry_moved = await advanceInquiry(inquiry, pc.inquiry_status, `Evenement "${b.title}" heeft plaatsgevonden op ${b.date}`);
        }
        await recordRun('post_event', key, 'booking', b.id, out);
      }
    }

    // ---------------------------------------------------- 5. inbound reply SLA
    if (isOn('inbound_reply_sla') && !bookingScope) {
      const ic = cfg<{ hours: number; assignees: string[] }>('inbound_reply_sla', { hours: 4, assignees: [] });
      const { data: convs } = await supabase
        .from('conversations')
        .select('id, user_id, contact_id, contact_name, last_message_direction, last_message_date, unread, last_message_body')
        .eq('unread', true).eq('last_message_direction', 'inbound');
      const now = new Date();
      for (const conv of convs || []) {
        if (!inboundOverdue(conv, now, Number(ic.hours) || 4)) continue;
        const stamp = String(conv.last_message_date).slice(0, 16);
        const key = `inbound:${conv.id}:${stamp}`;
        if (await hasRun(key)) continue;
        const contact = conv.contact_id ? contactById.get(conv.contact_id) : null;
        const name = contactName(contact) || conv.contact_name || 'Onbekend';
        const tpl: TaskTemplate = {
          id: 'inbound-reply', trigger: 'quote_sent', title: `Beantwoorden: bericht van ${name}`,
          description: `Onbeantwoord inkomend bericht sinds ${new Date(conv.last_message_date).toLocaleString('nl-NL', { timeZone: 'Europe/Amsterdam' })}.\n\n"${String(conv.last_message_body || '').slice(0, 300)}"`,
          anchor: 'trigger_date', offset_days: 0, assignees: Array.isArray(ic.assignees) ? ic.assignees : [], priority: 'high', enabled: true,
        };
        await createTasks(planTasks(tpl, `conversation:${conv.id}:${stamp}`, { today }), { contact_id: conv.contact_id, company_id: contact?.company_id || null }, conv.user_id || ownerId);
        await recordRun('inbound_reply_sla', key, 'conversation', conv.id, { contact_id: conv.contact_id });
      }
    }

    // ---------------------------------------------------------- 6. contact tags
    if (isOn('contact_tags') && !bookingScope) {
      const mapping = cfg<Record<string, string>>('contact_tags', {});
      const MAX_PUSHES = 50;
      let pushes = 0;
      for (const contact of contacts) {
        if (pushes >= MAX_PUSHES) break;
        const current: string[] = Array.isArray(contact.tags) ? contact.tags : [];
        const { tags, changed } = tagsForContactStatus(current, contact.status, mapping);
        if (!changed) continue;
        pushes++;
        if (dryRun) { results.contacts_updated++; continue; }
        const { error } = await supabase.from('contacts').update({ tags }).eq('id', contact.id);
        if (error) { results.errors.push(`tags:${contact.id}:${error.message}`); continue; }
        contact.tags = tags;
        results.contacts_updated++;
        // GHL stays the source of truth for the other tags: only add/remove the status tags
        if (ghlEnabled && contact.ghl_contact_id) {
          const lower = (arr: string[]) => arr.map((t) => t.toLowerCase());
          const added = tags.filter((t) => !lower(current).includes(t.toLowerCase()));
          const removed = current.filter((t) => !lower(tags).includes(t.toLowerCase()));
          try {
            await delay(150);
            if (added.length) {
              const res = await fetch(`${GHL_API_BASE}/contacts/${contact.ghl_contact_id}/tags`, { method: 'POST', headers: ghlHeaders, body: JSON.stringify({ tags: added }) });
              if (!res.ok) results.errors.push(`ghl-tags:${contact.id}:${await readError(res)}`); else await res.text();
            }
            if (removed.length) {
              const res = await fetch(`${GHL_API_BASE}/contacts/${contact.ghl_contact_id}/tags`, { method: 'DELETE', headers: ghlHeaders, body: JSON.stringify({ tags: removed }) });
              if (!res.ok) results.errors.push(`ghl-tags:${contact.id}:${await readError(res)}`); else await res.text();
            }
            results.ghl_tags_pushed++;
          } catch (e) { results.errors.push(`ghl-tags:${contact.id}:${String(e)}`); }
        }
      }
    }

    // ------------------------------------------------------------------ log
    const didSomething = results.tasks_created + results.inquiries_updated + results.bookings_updated + results.contacts_updated + results.options_warned + results.options_expired > 0;
    if (!dryRun && (didSomething || results.errors.length > 0 || body.source !== 'cron')) {
      await supabase.from('sync_log').insert({
        user_id: ownerId, entity_type: 'system', entity_id: null,
        action: 'crm-automations-run', details: { source: body.source || 'manual', ...results },
        status: results.errors.length ? 'error' : 'success',
      });
    }
    const publicResults = caller === 'user' ? results : { ...results, details: [] };
    return jsonResponse({ success: true, dry_run: dryRun, ...publicResults });
  } catch (e) {
    console.error('crm-automations error:', e);
    results.errors.push(String(e));
    return jsonResponse({ success: false, ...results }, 500);
  }
});

async function fetchAll(supabase: any, table: string, cols: string): Promise<any[]> {
  const rows: any[] = [];
  const PAGE = 1000;
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await supabase.from(table).select(cols).order('id').range(from, from + PAGE - 1);
    if (error || !data?.length) break;
    rows.push(...data);
    if (data.length < PAGE) break;
  }
  return rows;
}
